let products = [
    {
        id: 201,
        subject: "Art Club",
        location: "Art Room",
        price: 15,
        availableSpace: 10,
        image: "images/art_club.png",
        rating: 4,  
    },
    {
        id: 202,
        subject: "Drama Club",
        location: "Theatre 1",
        price: 20,
        availableSpace: 8,
        image: "images/drama_club.png",
        rating: 4,  
    },
    {
        id: 203,
        subject: "Coding Club",
        location: "Computer Lab 3",
        price: 10,
        availableSpace: 5,
        image: "images/code_club.png",
        rating: 4,  
    },
    {
        id: 204,
        subject: "Science Club",
        location: "Chemistry Lab",
        price: 12,
        availableSpace: 6,
        image: "images/sci_club.png",
        rating: 4,  
    },
    {
        id: 205,
        subject: "Music Club",
        location: "Music Room",
        price: 18,
        availableSpace: 12,
        image: "images/music_club.png",
        rating: 4,  
    },
    {
        id: 206,
        subject: "Maths Club",
        location: "Room 302",
        price: 18,
        availableSpace: 16,
        image: "images/math_club.png",
        rating: 4,  
    },
    {
        id: 207,
        subject: "Language Club",
        location: "Room 121",
        price: 18,
        availableSpace: 8,
        image: "images/lang_club.png",
        rating: 4,  
    },
    {
        id: 208,
        subject: "Photography Club",
        location: "Studio 2",
        price: 22,
        availableSpace: 9,
        image: "images/photo_club.png",
        rating: 4,  
    },
    {
        id: 209,
        subject: "Chess Club",
        location: "Library 2",
        price: 10,
        availableSpace: 14,
        image: "images/chess_club.png",
        rating: 4,  
    },
    {
        id: 210,
        subject: "Robotics Club",
        location: "Tech Lab 2",
        price: 25,
        availableSpace: 7,
        image: "images/robo_club.png",
        rating: 4,  
    },
    {
        id: 211,
        subject: "Baking Club",
        location: "Kitchen 1",
        price: 20,
        availableSpace: 10,
        image: "images/baking_club.png",
        rating: 4,  
    },
    {
        id: 213,
        subject: "Gardening Club",
        location: "South-East Garden",
        price: 12,
        availableSpace: 6,
        image: "images/garden_club.png",
        rating: 4,  
    },
    {
        id: 214,
        subject: "Dance Club",
        location: "Dance Studio",
        price: 18,
        availableSpace: 10,
        image: "images/dance_club.png",
        rating: 4,  
    },
]